# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "m-k8s" do |cfg|
        cfg.vm.box = "sysnet4admin/CentOS-k8s"
        cfg.vm.provider "virtualbox" do |vb|
            vb.name = "m-k8s(github_SysNet4Admin)"
            vb.cpus = 2
            vb.memory = 2048
            vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]
        end
        cfg.vm.host_name = "m-k8s"
        cfg.vm.network "private_network", ip: "192.168.1.10"
        cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "install_pkg.sh"
        cfg.vm.provision "file", source: "ping_2_nds.sh", destination: "ping_2_nds.sh"
        # 파일을 게스트 운영 체제에 전달하기 위해 "shell"이 아닌 "file" 구문으로 변경, 이렇게 하면 게스트의 홈 디렉터리로 파일을 전달한다.
        cfg.vm.provision "shell", path: "config.sh"
    end

    #=============#
    # Added Nodes #
    #=============#

    (1..3).each do |i| # 1부터 3까지 i에 입력하면서 반복
        config.vm.define "w#{i}-k8s" do |cfg| # {i}값이  1,2,3으로 차례대로 치환됨
            cfg.vm.box = "sysnet4admin/CentOS-k8s"
            cfg.vm.provider "virtualbox" do |vb|
                vb.name = "w#{i}-k8s(github_SysNet4Admin)"
                vb.cpu = 1
                vb.memory = 1024
                vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]
            end
            cfg.vm.host_name = "w#{i}-k8s"
            cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
            cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "install_pkg.sh"
        end
    end
end