Vagrant.configure("2") do |config|
    # 5 줄 -> "2"는 베이그런트에서 루비로 코드를 읽어 들여 실행할 때 작동하는 API버전
    # do |name| ~ end 는 name의 시작과 끝을 나타낸다. 파이썬처럼 들여쓰기로 구분한다.
    # do |config| 는 베이그런트 설정의 시작을 나타낸다.
  
    config.vm.box = "sysnet4admin/CentOS-k8s"
    # 가상환경 이미지를 "sysnet4admin/CentOS-k8s"로 선택
end
